### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by vadymboichenkoAcupower**
- [DEMO LINK](https://vadymboichenkoAcupower.github.io/layout_calendar/)
- [TEST REPORT LINK](https://vadymboichenkoAcupower.github.io/layout_calendar/report/html_report/)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Hey, code looks good but demo doesn't work, try to run "npm run deploy" and check if it works.

If you have any questions - feel free to ask them in fe_chat

**Comment by vadymboichenkoAcupower** [comment]
Made deploy. Try again

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
- check month-length modifier.
now always visible in one day less than in modifier
Screenshot from 2023-06-24 17-08-33

- 
Screenshot from 2023-06-24 17-11-15

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Previous comments have not been corrected
if you have any questions feel free in fe_cat

**Pull request closed without merging**
