### PR TITLE
layout-calendar 

### PR DESCRIPTION
**Pull request by georgiyevv**
- [DEMO LINK] (https://svyatoslavPy.github.io/layout_calendar/)

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
watch a video how your app should work

https://www.loom.com/share/3dcf1ba5147f45139ef2d1a0d340b0d3?sid=40904cbf-2f19-4cd5-b9ea-05535b0e89fc

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
It seems like you haven't pushed any changes. Also, the Demo link doesn't work:

image

Make sure demo link works (ask for help in the chat if you have problems with deployment) push changes and re-request review then

**Comment by TarasHoliuk** [comment]
Here is a sign that you pushed something (it was your first solution):

image

But here is no such sign before re-requesting review:

Screenshot from 2024-01-29 19-14-50

Make sure you added all changes, made a commit, and pushed it (without errors - successfully). And **after** these actions re-request review

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
If you have **any** questions, or are faced with problems during commit/push command - ask for help in the chat.

This [instruction](https://github.com/mate-academy/layout_task-guideline#how-to-solve-the-layout-tasks-on-github) might be helpfull

**Comment by georgiyevv** [comment]
maybe you don't clear  cookie, because site not updating in your browser.

**Review by lerastarynets — COMMENTED** [review]
This was the first time I open your site, which means I have no cookies, but I still see error 404, pls fix

**Pull request closed without merging**
