### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by MariannaBo**
- [DEMO LINK](https://MariannaBo.github.io/layout_calendar/)
- [TEST REPORT LINK](https://MariannaBo.github.io/layout_calendar/report/html_report/)

### CODE REVIEW

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
please deploy your changes, demo link isn't working
also don't add all css and css.map files to the pr, you don't need to turn scss files into css ones, when you start `npm start` it will do it for you automatically

**Comment by MariannaBo** [comment]
- [DEMO LINK](https://MariannaBo.github.io/layout_calendar/)

**Comment by MariannaBo** [comment]
> 

I don't understand why the demo link doesn't work. 
npm start works fine

**Review by mykhalenych — CHANGES_REQUESTED** [review]
demo link isn't working, if you have questions add them to chat

**Pull request closed without merging**
