### PR TITLE
Add Calendar

### PR DESCRIPTION
**Pull request by ghost**
- [DEMO LINK](https://ruslanpashkov.github.io/layout_calendar/)

### CODE REVIEW

**Review by generatedman — COMMENTED** [review]
good job!

**Review by generatedman — APPROVED** [review]
good job!

**Review by naziamoff — CHANGES_REQUESTED** [review]
In general - good, but can be better.

- Seems it is not properly aligned and breaks at some point
Screenshot 2023-04-19 at 13 03 27

**Review by naziamoff — APPROVED** [review]
🔥

**Pull request closed without merging**
