### PR TITLE
Calendar built

### PR DESCRIPTION
**Pull request by Sergei-Nikolaienko**
https://Sergei-Nikolaienko.github.io/layout_calendar/
https://Sergei-Nikolaienko.github.io/layout_calendar/report/html_report/

### CODE REVIEW

**Review by Virass — CHANGES_REQUESTED** [review]
run command `npm run deploy` for deploying your demo

**Comment by Sergei-Nikolaienko** [comment]
> 

deploying finished

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Re-check deployment, because I can't see your project by the provided link 
Screenshot 2022-11-21 at 16 09 52

**Comment by Sergei-Nikolaienko** [comment]
> Re-check deployment, because I can't see your project by the provided link Screenshot 2022-11-21 at 16 09 52

image

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
set the calendar in the middle of the pageScreenshot 2022-11-22 at 17 46 28

**Review by Viktor-Kost — APPROVED** [review]
GJ!

**Pull request closed without merging**
